// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtldnjtcnlululyfhghj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bGRuanRjbmx1bHVseWZoZ2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDU0NDAsImV4cCI6MjA2OTQyMTQ0MH0.TIc3MdIvIN3IrEvnxH9_wCd_oBOy-79UKxZmSHuKriA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});